# Generated by Django 6.0.5 on 2026-05-26 01:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement'), ('utility', 'Utility / Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('original_filename', models.CharField(max_length=512)),
                ('file_content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending parse'), ('parsing', 'Parsing'), ('review', 'Awaiting review'), ('approved', 'Approved'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parser_version', models.CharField(default='1.0', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 — Direct'), ('2', 'Scope 2 — Electricity'), ('3', 'Scope 3 — Value chain')], max_length=1)),
                ('category', models.CharField(choices=[('fuel_diesel', 'Diesel'), ('fuel_petrol', 'Petrol / Gasoline'), ('fuel_natural_gas', 'Natural gas'), ('fuel_lpg', 'LPG'), ('fuel_other', 'Other fuel'), ('electricity', 'Grid electricity'), ('travel_flight_short', 'Flight — short haul (<3h)'), ('travel_flight_long', 'Flight — long haul (≥3h)'), ('travel_hotel', 'Hotel stay'), ('travel_car_rental', 'Car rental / ground'), ('travel_rail', 'Rail'), ('travel_other', 'Other travel'), ('procurement', 'Procurement / supply chain')], max_length=40)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('raw_unit', models.CharField(max_length=50)),
                ('raw_description', models.TextField(blank=True)),
                ('quantity_normalised', models.DecimalField(decimal_places=4, max_digits=18)),
                ('normalised_unit', models.CharField(max_length=20)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('emission_factor_used', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited by analyst')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('analyst_note', models.TextField(blank=True)),
                ('source_row_id', models.CharField(blank=True, max_length=100)),
                ('is_locked', models.BooleanField(default=False)),
                ('flags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.ingestionbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-activity_date', 'category'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('batch_uploaded', 'Batch uploaded'), ('batch_parsed', 'Batch parsed'), ('batch_failed', 'Batch parse failed'), ('record_approved', 'Record approved'), ('record_rejected', 'Record rejected'), ('record_edited', 'Record edited'), ('batch_approved', 'Batch approved (all records locked)'), ('record_unlocked', 'Record unlocked for correction')], max_length=30)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.emissionrecord')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.ingestionbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_plant_code', models.CharField(max_length=10)),
                ('display_name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='ingestion.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'sap_plant_code')},
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('analyst', 'Analyst'), ('admin', 'Admin'), ('auditor', 'Auditor (read-only)')], default='analyst', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ingestion.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
