[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate",
  "python seed_data.py"
]

[start]
cmd = "gunicorn breathe_esg.wsgi --workers 2 --bind 0.0.0.0:$PORT --timeout 60"
